services:
  quizlet_be:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quizlet_be
    ports:
      - 8081:8081
    env_file:
      - .env
    depends_on:
      - quizlet_db
  quizlet_db:
    container_name: quizlet_db
    image: postgres:17
    restart: always
    env_file:
      - .env
    ports:
      - 5433:5432
    volumes:
      - quizlet_db:/var/lib/postgresql/data

volumes:
  quizlet_db:
    driver: local