name: "Flyway Migration"

on:
  push:
    branches:
      - master
      - feature/pipeline-flyway-migration

jobs:
  flwayMigration:
    runs-on: [ubuntu-latest]
    env:
      FLYWAY_URL: jdbc:postgresql://localhost:5432/mydb
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: postgres
      FLYWAY_LOCATIONS: filesystem:src/main/resources/ini_data/migration/COMMON
    defaults:
      run:
        working-directory: quizlet-be
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Flyway
        run: |
          sudo apt update
          sudo apt install snapd
          sudo snap install flyway
          flyway -v

      # - name: Run Flyway
      #   run: |
      #     docker run --rm \
      #       --name quizlet_flyway-db \
      #       --network quizlet-be_default \
      #       -e FLYWAY_PASSWORD=postgres \
      #       -e FLYWAY_URL=jdbc:postgresql://quizlet_db:5432/quizlet_db \
      #       -e FLYWAY_USER=postgres \
      #       -e FLYWAY_SCHEMAS=public \
      #       -v $(pwd):/flyway/sql \
      #     flyway/flyway:latest

      # - name: Run Flyway Info
      #   run: |
      #     dokcer exec -it quizlet_flyway-db bash
      #     docker run --rm \
      #       --network quizlet-be_default \
      #       -e FLYWAY_PASSWORD=postgres \
      #       -e FLYWAY_URL=jdbc:postgresql://quizlet_db:5432/quizlet_db \
      #       -e FLYWAY_USER=postgres \
      #       -e FLYWAY_SCHEMAS=public \
      #       -v $(pwd):/flyway/sql \
      #     flyway/flyway:latest info

      # - name: Run Flyway validate
      #   run: |

      # - name: Run Flyway Migrations
      #   run: |
      #     docker run --rm \
      #       --network quizlet-be_default \
      #       -e FLYWAY_PASSWORD=postgres \
      #       -e FLYWAY_URL=jdbc:postgresql://quizlet_db:5432/quizlet_db \
      #       -e FLYWAY_USER=postgres \
      #       -e FLYWAY_SCHEMAS=public \
      #       -v $(pwd):/flyway/sql \
      #     flyway/flyway:latest migrate
